# Generated by Django 3.2.10 on 2021-12-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palettes', '0006_alter_favorites_saved_by'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_palettes',
            field=models.ManyToManyField(related_name='saved_palettes', to='palettes.Palette'),
        ),
    ]
