# Generated by Django 3.2.10 on 2021-12-30 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_saved_palettes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='saved_palettes',
        ),
    ]
