# Generated by Django 3.2.10 on 2021-12-29 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('hex', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('primary_color1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary1', to='palettes.color')),
                ('primary_color2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary2', to='palettes.color')),
                ('secondary_color1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary1', to='palettes.color')),
                ('secondary_color2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondary2', to='palettes.color')),
                ('secondary_color3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary3', to='palettes.color')),
                ('secondary_color4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary4', to='palettes.color')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palette', models.ManyToManyField(limit_choices_to={'is_public': True}, related_name='favorites', to='palettes.Palette')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='palette',
            constraint=models.UniqueConstraint(fields=('primary_color1', 'primary_color2', 'secondary_color1', 'secondary_color2', 'secondary_color3', 'secondary_color4'), name='unique_palette'),
        ),
    ]
