# Generated by Django 3.2.10 on 2021-12-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palettes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palette',
            name='primary_colors',
            field=models.ManyToManyField(related_name='dominant', to='palettes.Color'),
        ),
        migrations.AddField(
            model_name='palette',
            name='secondary_colors',
            field=models.ManyToManyField(related_name='accent', to='palettes.Color'),
        ),
    ]
