# Generated by Django 3.2.10 on 2021-12-29 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palettes', '0002_auto_20211229_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palette',
            name='primary_colors',
        ),
        migrations.RemoveField(
            model_name='palette',
            name='secondary_colors',
        ),
        migrations.AlterField(
            model_name='palette',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
