# Generated by Django 3.2.10 on 2021-12-30 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palettes', '0008_palette_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='palette',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='saved_by',
        ),
        migrations.DeleteModel(
            name='Favorite_Palettes',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
